### ISSUE TITLE
Fails with some animations

### ISSUE THREAD

**Issue by sonaye** [sonaye/lottie-editor#1]
e.g. https://labs.nearpod.com/bodymovin/demo/the_lady/data.json

**Comment by sonaye** [comment]
Kindly add any animations that are not working here.

**Comment by pedro-valentim** [comment]
e.g. https://www.lottiefiles.com/storage/datafiles/zD38ARIXZ4BLYKB/data.json

**Comment by chrisgannon** [comment]
Drag and drop not working - Win 10, Chrome (latest)

**Comment by sonaye** [comment]
@chrisgannon Seems to be related to https://github.com/react-dropzone/react-dropzone/issues/144#issuecomment-249129868, will look into this.

**Comment by anguyen1817** [comment]
I tried with this one https://www.lottiefiles.com/109-bouncy-loader and the colors couldn't be found. Btw, thanks so much for working on this!

**Comment by edalbosco** [comment]
https://www.lottiefiles.com/198-volume-indicator

**Comment by johncharris** [comment]
https://www.lottiefiles.com/download/997

**Comment by uditguru** [comment]
https://www.lottiefiles.com/147-outline-user

**Comment by uditguru** [comment]
https://www.lottiefiles.com/1466-notification
