### ISSUE TITLE
Editor doesn't allow me to change the colors of the animation

### ISSUE THREAD

**Issue by henriqrossatto** [sonaye/lottie-editor#13]
I did a some lottie animations and when I go to editor, didn't appear any layer for me in case I want change the color after the exportation. The animations run normally on preview. What am I doing wrong?

I'm attaching the files and the a screenshot. Anyone can help me?

[LottieEditor_error_files.zip](https://github.com/sonaye/lottie-editor/files/1634958/LottieEditor_error_files.zip)

![lottie editor error](https://user-images.githubusercontent.com/30601233/34987746-6b823186-faa3-11e7-92fc-e5d88d85a2fe.jpg)

**Comment by sonaye** [comment]
Not all cases are supported yet, see #1.

I looked into your JSON, you have two `[0, 0, 0, 1]` instances which are responsible for the black color. Change to your `rgb(R, G, B)` color by replacing them with `[R / 255, G / 255, B / 255, 1]`.

**Comment by henriqrossatto** [comment]
I found the error. The problem was the path.

Thanks for the feedback!
