### ISSUE TITLE
Number of Frames

### ISSUE THREAD

**Issue by CassianoMouraLeao** [sonaye/lottie-editor#14]
Can I know the number of frames on json animation?

**Comment by sonaye** [comment]
Not really sure, perhaps you could ask [here](https://github.com/airbnb/lottie-web/issues).

**Comment by sonaye** [comment]
I saw the response here https://github.com/airbnb/lottie-web/issues/839, I don't see how this can be helpful to display in the editor, care to elaborate on some use cases?
