### ISSUE TITLE
Cannot download Edited animation

### ISSUE THREAD

**Issue by shekhar707** [sonaye/lottie-editor#16]
when try to download, give below text pops up.
![screenshot from 2018-02-04 13-27-49](https://user-images.githubusercontent.com/22654660/35775482-5b0715a4-09af-11e8-86b1-01829b224589.png)

**Comment by sonaye** [comment]
And it doesn't download?

**Comment by rana01645** [comment]
Yes, It doesn't download :(

**Comment by rana01645** [comment]
Problem was with only mozilla firefox, In google chrome its working fine
