### ISSUE TITLE
Editor doesn't allow me to change the colors of the animation

### ISSUE THREAD

**Issue by lalararalala** [sonaye/lottie-editor#18]
I did a some lottie animations and when I go to editor, didn't appear any layer for me in case I want change the color. The animations run normally on preview. Anyone can help me?
The anination URL is 
https://editor.lottiefiles.com/?src=https://www.lottiefiles.com/download_public/322

**Comment by sonaye** [comment]
Unfortunately not all the Lottie features are supported yet. The tool works for simple animations that are structured without too many layers of complexity (it depends on your AE file). I am referencing this in #1 so that it can be tested whenever new features added.
