### ISSUE TITLE
failed to edit

### ISSUE THREAD

**Issue by halynexpi** [sonaye/lottie-editor#20]
https://www.lottiefiles.com/1870-check-mark-done

i can't edit this lottie file, an error has occurred.
i really need to change the color :C

**Comment by sonaye** [comment]
I believe this is an edge case where color extraction for it is not supported yet (there are plenty of those). Your best option at the moment would be to debug manually, maybe this comment https://github.com/airbnb/lottie-web/issues/704#issuecomment-348243972 can help with that.
