### ISSUE TITLE
Can't change color of some elements

### ISSUE THREAD

**Issue by FedeGens** [sonaye/lottie-editor#22]
Hi,
I tried using Lottie Editor with this file:

https://www.lottiefiles.com/search?q=empty

but it allows me to change just one stroke color as shown here :(
<img width="1669" alt="schermata 2018-06-22 alle 17 13 55" src="https://user-images.githubusercontent.com/22976202/41784437-f6ac95ea-763f-11e8-8474-f55a3a8cf13f.png">

**Comment by sonaye** [comment]
Hi, it seems that color extraction is not supported for this one yet (there are plenty of unsupported cases), the editor works with simple animations. Maybe try debugging it manually?
