### ISSUE TITLE
Please add package-lock.json - Material ui is broken

### ISSUE THREAD

**Issue by evanjmg** [sonaye/lottie-editor#26]
<img width="1206" alt="screen shot 2018-09-11 at 4 49 00 pm" src="https://user-images.githubusercontent.com/9342155/45371470-9b725d80-b5e2-11e8-8e62-62991c26b229.png">

**Comment by sonaye** [comment]
Hi, can you try building from `master` branch instead of `dev`? which is not stable.

**Comment by evanjmg** [comment]
I just `npm install babel-runtime --save-dev`and this resolve my issue
