### ISSUE TITLE
Diff is available in the console.

### ISSUE THREAD

**Issue by iToxicDeveloper** [sonaye/lottie-editor#27]
I recently edited a LottieFile.. but when I click the download button it says "Diff is available in the console."
what does it mean ? and how can I download the edited file ?

**Comment by sonaye** [comment]
When you make some changes, you can see what exactly was changed in the JSON file (extra dev option):

![screen shot 2018-10-17 at 8 36 41 pm](https://user-images.githubusercontent.com/23000873/47105391-75c51d80-d24c-11e8-985f-94abc97ee5b4.png)

You can download the updated file by clicking the download icon bellow the animation (icon with down arrow), are you facing any issues with that?

**Comment by sonaye** [comment]
If the file is not downloading, it's likely that you are not using a Chrome, I've had a similar report on this before, can you try using Crome? The bug should be fixed in the next release (still in the works).

**Comment by iToxicDeveloper** [comment]
It's working on chrome! thank you!
