### ISSUE TITLE
Editor is down

### ISSUE THREAD

**Issue by Crysis21** [sonaye/lottie-editor#28]
It seems the editor is no longer working. I receive a firebase error, as the application has not been deployed.

**Comment by sonaye** [comment]
Try https://bodymovin-editor.firebaseapp.com, this seems to be an issue related to the domain, I need to reach out to the Lottie Files team to figure it out.

**Comment by sonaye** [comment]
@reallynattu Can you reach out to me please, I couldn’t find any email for contact. Thanks.

**Comment by Crysis21** [comment]
thank you, I can use it now. I spent a lot of time modifying colors in json. Great work!

**Comment by reallynattu** [comment]
@sonaye hey sent you a mail to the email on your profile.

**Comment by sonaye** [comment]
Working now https://editor.lottiefiles.com.
